# This is the main Jekyll configuration file for the documentation site.
# It contains settings for the site, including the theme, author information, and GitHub repository details.
# It also includes settings for plugins like Mermaid for diagrams and charts.

title: AAAA Stack
description: Angular, ASP.NET, AWS and Azure AD
author: "Ravi Mohan"

theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/images/logo.png

mermaid: true

github:
  public: true
  is_project_page: true
  repository_url: https://github.com/sravimohan/aaaa-stack
  owner_name: Ravi Mohan
  owner_url: https://github.com/sravimohan
