# AWSTemplateFormatVersion: "2010-09-09"
# Description: "GitHub Actions OIDC Provider Permissions"
#
# Sample instructions to run this CloudFormation template using AWS CLI:
#
# To create the stack:
#   aws cloudformation create-stack --stack-name GitHubActionsPermissionsStack --template-body file://github-actions-permissions.yaml --parameters ParameterKey=GitHubOrg,ParameterValue=sravimohan ParameterKey=GitHubRepo,ParameterValue=aaaa-stack --capabilities CAPABILITY_IAM
#
# To update the stack, use:
#   aws cloudformation update-stack --stack-name GitHubActionsPermissionsStack --template-body file://github-actions-permissions.yaml --parameters ParameterKey=GitHubOrg,ParameterValue=<your-github-org> ParameterKey=GitHubRepo,ParameterValue=<your-github-repo> --capabilities CAPABILITY_IAM
#
# To delete the stack, use:
#   aws cloudformation delete-stack --stack-name GitHubActionsPermissionsStack

AWSTemplateFormatVersion: "2010-09-09"
Description: "GitHub Actions OIDC Provider Permissions"

Parameters:
  GitHubOrg:
    Type: String
    Description: "The GitHub organization"
  GitHubRepo:
    Type: String
    Description: "The GitHub repository"

Resources:
  GitHubActionsOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"

  GitHubActionsOIDCProviderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: !Ref GitHubActionsOIDCProvider
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOrg}/${GitHubRepo}:ref:*"
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
      Policies:
        - PolicyName: "ECRPolicy"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action: "ecr:*"
                Resource: "*"