# This GitHub Actions workflow builds and tests the application, then publishes it to an Amazon ECR repository.
# It is triggered on manual dispatch or when changes are pushed to the configured branches.
# Required Secrets:
# - AWS_REGION: AWS region where the ECR repository is located (e.g., us-west-2).
# - AWS_BUILD_ROLE_ARN_TO_ASSUME: The ARN of the IAM role to assume for GitHub Actions.
# - AWS_ECR_REPOSITORY_URI: The URI of the ECR repository (e.g., 999999999999.dkr.ecr.ap-southeast-2.amazonaws.com/aaaa-stack).

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore Dependencies
        run: dotnet restore ./src/AAAA.Server/AAAA.Server.csproj

      - name: Build Project
        run: dotnet build ./src/AAAA.Server/AAAA.Server.csproj --no-restore

      - name: Run Tests
        run: dotnet test ./src/AAAA.Server/AAAA.Server.csproj --no-build --verbosity normal

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_BUILD_ROLE_ARN_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Publish Docker Image to Amazon ECR
        working-directory: ./src/AAAA.Server/
        run: |
          dotnet publish -c Release -p:ContainerRepository="${{ secrets.AWS_ECR_REPOSITORY_URI }}" -p:ContainerImageTags="${{ github.ref_name }}-${{github.sha}};" -p:RuntimeIdentifier=linux-x64
          docker push ${{ secrets.AWS_ECR_REPOSITORY_URI }} --all-tags
