# This GitHub Actions workflow deploys to AWS ECS Fargate Cluster.
# It is triggered on manual dispatch.
# Required Secrets:
# - AWS_ACCOUNT_ID: The AWS account ID where the resources are deployed.
# - AWS_REGION: AWS region where the ECR repository is located (e.g., us-west-2).
# - AWS_DEPLOY_ROLE_ARN_TO_ASSUME: The ARN of the IAM role to assume for GitHub Actions.
# - AWS_ACM_CERTIFICATE_ARN: The ARN of the ACM certificate for the load balancer.
# - AWS_ECR_REPOSITORY_URI: The URI of the ECR repository (e.g., 999999999999.dkr.ecr.ap-southeast-2.amazonaws.com/aaaa-stack).

name: Deploy

on:
  workflow_dispatch:
    inputs:
      ecrImageTag:
        description: "ECR Image tag to deploy"
        required: false
        default: ""
  push:
    branches:
      - ci

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN_TO_ASSUME }}

      # Set the image tag to use (input parameter or default to branch name + commit SHA)
      - name: Set ECR Image Tag to be used
        id: ecr-image-tag-step
        run: |
          if [ -z "${{ github.event.inputs.ecrImageTag }}" ]; then
            ECR_IMAGE_TAG="${{ github.ref_name }}-${{ github.sha }}"
          else
            ECR_IMAGE_TAG="${{ github.event.inputs.ecrImageTag }}"
          fi

          echo "Using ECR image tag: $ECR_IMAGE_TAG"
          echo "ECR_IMAGE_TAG=$ECR_IMAGE_TAG" >> "$GITHUB_OUTPUT"

      # OPTIONAL: Login to Amazon ECR, to check if the image exists
      # This step is optional and can be removed if you don't need to check for the image existence.
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # OPTIONAL: docker pull, to check if the image exists
      # This step is optional and can be removed if you don't need to check for the image existence.
      - name: Check if image exists in ECR
        run: |
          echo "Checking if image with tag ${{ steps.ecr-image-tag-step.outputs.ECR_IMAGE_TAG }} exists in ECR..."
          docker pull "${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ steps.ecr-image-tag-step.outputs.ECR_IMAGE_TAG }}"

      # Setup Node.js for AWS CDK
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Deploy with AWS CDK
      - name: Deploy with AWS CDK
        working-directory: ./aws/app-cdk
        run: |
          ECR_IMAGE_TAG="${{ steps.ecr-image-tag-step.outputs.ECR_IMAGE_TAG }}"
          npm ci
          npx cdk deploy --all --require-approval never \
            --parameters AcmCertificateArn="${{ secrets.AWS_ACM_CERTIFICATE_ARN }}" \
            --parameters EcrRepositoryUri="${{ secrets.AWS_ECR_REPOSITORY_URI }}" \
            --parameters EcrImageTag="$ECR_IMAGE_TAG"
        env:
          # environment variables needed for CDK deployment
          CDK_DEFAULT_ACCOUNT: "${{ secrets.AWS_ACCOUNT_ID }}"
          CDK_DEFAULT_REGION: "${{ secrets.AWS_REGION }}"
