# This GitHub Actions workflow deploys to AWS ECS Fargate Cluster.
# It is triggered on manual dispatch.
# Required Secrets:
# - AWS_REGION: AWS region where the ECR repository is located (e.g., us-west-2).
# - AWS_DEPLOY_ROLE_ARN_TO_ASSUME: The ARN of the IAM role to assume for GitHub Actions.
# - AWS_ECR_REPOSITORY_URI: The URI of the ECR repository (e.g., 999999999999.dkr.ecr.ap-southeast-2.amazonaws.com/aaaa-stack).

name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Setup Node.js for AWS CDK
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Deploy with AWS CDK
      - name: Deploy with AWS CDK
        working-directory: ./aws/app-cdk
        run: |
          npm ci
          npm run cdk deploy -- --require-approval never
        env:
          # environment variables needed for CDK deployment
          CDK_STACK_NAME: "${{ github.ref_name }}-dev"
          CDK_DEFAULT_ACCOUNT: "${{ secrets.AWS_ACCOUNT_ID }}"
          CDK_DEFAULT_REGION: "${{ secrets.AWS_REGION }}"
          # IMAGE_TAG: "${{ github.ref_name }}-${{ github.sha }}"
          IMAGE_TAG: "main-5590113d775a5ab2a910f473e1d6a82fc3fcd64b"
          ECR_REPOSITORY_URI: "${{ secrets.AWS_ECR_REPOSITORY_URI }}"
